# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_INGENIC_CGU_COMMON)	+= cgu.o pm.o
obj-$(CONFIG_INGENIC_CGU_JZ4740)	+= jz4740-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4725B)	+= jz4725b-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4770)	+= jz4770-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4780)	+= jz4780-cgu.o
obj-$(CONFIG_INGENIC_TCU_CLK)		+= tcu.o
obj-$(CONFIG_COMMON_CLK) += clk.o clk-pll.o clk-div.o clk-bus.o power-gate.o
obj-$(CONFIG_SOC_X2000_V12)	+= clk-x2000-v12.o
obj-$(CONFIG_SOC_T40)	+= clk-t40.o
obj-$(CONFIG_SOC_T31)	+= clk-t31.o